# This is a basic workflow to help you get started with Actions

name: RC Create Pull Request

# Controls when the workflow will run
on:
  create:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CreateCandidatePR:
    if: ${{ contains(github.ref, 'refs/heads/release-candidate/**') }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ steps.extract_branch.outputs.branch }}

      # Make changes to pull request here
      - name: Create RC Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: Release candidate ${{ steps.extract_branch.outputs.branch }}
          title: RC-${{ steps.extract_branch.outputs.branch }}
          labels: RC-${{ steps.extract_branch.outputs.branch }}, release-candidate
          branch: ${{ steps.extract_branch.outputs.branch }}
          base: master
