name: Rollback Flow

# Controls when the workflow will run
on:
  # Triggers only when a PR is merged on hmg
  pull_request:
    branches:
      - hmg
    types: [closed]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CreateRollback:
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.head.ref, 'rollback/') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Create Branch for Rollback
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          branch: rollback/${{ github.event.pull_request.head.ref}}

      - name: Commit Rollback to branch
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git reset ${{ github.event.pull_request.merge_commit_sha }} --hard
          git push -f origin HEAD:rollback/${{ github.event.pull_request.head.ref }}
