name: Create HMG Flow

# Controls when the workflow will run
on:
  # Triggers only when a PR is merged on hmg
  pull_request_review:
  pull_request:
  discussion_comment:
    branches:
      - master
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CreateHMGCandidate:
    if: |
      contains(github.event.pull_request.head.ref, 'rollback/') == false &&
      github.action == 'created' &&
      contains(github.event.comment.body, 'create-hmg') == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Create Branch For Hmg Candidate
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          branch: hmg/${{ github.event.pull_request.head.ref }}

      # create the PR-HMG
      - name: Create HMG Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "hmg"
          source_branch: hmg/${{ github.event.pull_request.head.ref }}
          github_token: ${{ secrets.PAT }}
          pr_label: hmg-candidate
          pr_title: HMG | ${{ github.event.pull_request.title }}
          pr_body: ${{ github.event.pull_request.body }}
