# This is a basic workflow to help you get started with Actions

name: RC Create Branch

# Controls when the workflow will run
on:
  # Triggers only when a PR is open on hmg
  pull_request:
    branches:
      - hmg
    types: [opened]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CreateCandidateBranch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          branch: release-candidate/${{ github.event.number }}
