name: Create HMG Flow

# Controls when the workflow will run
on:
  pull_request:
  issue_comment:
    types: [created]
jobs:
  CreateHMGCandidate:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.html_url, '/pull/') &&
      contains(github.event.comment.body, 'create-hmg')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        id: get-pr
        with:
          script: |
            try {
              console.log(context)
              const result = await github.request(context.payload.issue.html_url)
              console.log(result.data)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.ref }} # or .head.ref for branch name
          fetch-depth: 0

      - name: Create Branch For Hmg Candidate
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          branch: hmg/${{ fromJSON(steps.get-pr.outputs.result).head.ref }}

      # create the PR-HMG
      - name: Create HMG Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "hmg"
          source_branch: hmg/${{ fromJSON(steps.get-pr.outputs.result).head.ref }}
          github_token: ${{ secrets.PAT }}
          pr_label: hmg-candidate
          pr_title: HMG | ${{ fromJSON(steps.get-pr.outputs.result).title }}
          pr_body: ${{ fromJSON(steps.get-pr.outputs.result).body }}
