# This is a basic workflow to help you get started with Actions

name: RC Create Branch

# Controls when the workflow will run
on:
  # Triggers only when a PR is merged on hmg
  pull_request:
    branches:
      - hmg
    types: [closed]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CreateCandidateBranch:
    if: github.event.pull_request.merged == true && ${{ contains(github.ref, 'refs/heads/revert') == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create Branch For Release Candidate
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          branch: release-candidate/${{ github.event.number }}

      # create the PR-RC
      - name: Create RC Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: release-candidate/${{ github.event.number }}
          github_token: ${{ secrets.PAT }}
          pr_label: release-candidate
          pr_title: RC-${{ github.event.number }}
          pr_body: ${{ github.event.pull_request.body }}

      - name: Create Branch for Rollback
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          branch: rollback/${{ github.event.number }}

      - name: Commit Rollback to branch
        run: |
          echo "$GITHUB_MERGE_CONTEXT"| jq '.event.commits[].id' | tail -1 | head -1 |sed 's/\"//g'
          git config --global user.name 'Rollback CI'
          git revert -m 1 $GITHUB_MERGE_CONTEXT --no-edit
          git push -f origin HEAD:rollback/${{ github.event.number }}
        env:
          GITHUB_MERGE_CONTEXT: ${{ toJson(github) }}

      # create the PR-Rollback
      - name: Create RC Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "hmg"
          source_branch: rollback/${{ github.event.number }}
          github_token: ${{ secrets.PAT }}
          pr_label: rollback
          pr_title: Rollback-${{ github.event.number }}
          pr_body: This pull request will revert the changes made by @${{ github.event.pull_request.user.login }} in branch ${{ github.event.pull_request.head.ref }}
